import type { City } from '@/lib/types'
import type { Destination, Route } from './types'

/* Route builders. Hours are approximate door-to-door, costs are approximate
 * return fares per person. Everything here is labelled as an estimate in the UI. */

type Flags = { overnight?: boolean; early?: boolean }

const fl = (hours: number, cost: number, note: string, f: Flags = {}): Route => ({
  mode: 'flight', hours, cost, overnight: f.overnight ?? false, earlyDeparture: f.early ?? false, note,
})
const tr = (hours: number, cost: number, note: string, f: Flags = {}): Route => ({
  mode: 'train', hours, cost, overnight: f.overnight ?? false, earlyDeparture: f.early ?? false, note,
})
const rd = (hours: number, cost: number, note: string, f: Flags = {}): Route => ({
  mode: 'road', hours, cost, overnight: f.overnight ?? false, earlyDeparture: f.early ?? false, note,
})

const routes = (r: Record<City, Route[]>) => r

export const DESTINATIONS: Destination[] = [
  {
    id: 'goa',
    name: 'Goa',
    region: 'West coast',
    blurb: 'Beaches on tap, the best food scene on the coast, and as much or as little nightlife as you want.',
    vibes: ['beach', 'nightlife', 'food', 'relaxation'],
    nightlife: 'strong',
    dailyCost: { budget: 2200, mid: 5200, premium: 11000 },
    stayTypes: { budget: 'Hostels and shared guesthouses in Anjuna or Palolem', mid: 'Mid-range hotels and boutique stays in Assagao or Colva', premium: 'Private villas and resorts in Ashwem or Cavelossim' },
    bestMonths: [10, 11, 12, 1, 2, 3],
    idealDays: [3, 7],
    octoberRating: 'excellent',
    octoberNote: 'Monsoon is over, the crowds have not arrived, and shacks are reopening.',
    routes: routes({
      mumbai: [fl(3, 6000, 'Direct flight, then about 45 min to the north beaches'), tr(11, 1400, 'Konkan Railway, the practical services run through the night', { overnight: true }), rd(10, 1800, 'Overnight sleeper bus down the coast', { overnight: true })],
      delhi: [fl(4.5, 9000, 'Direct flight, then a transfer to the beaches'), tr(26, 2200, 'Two nights on the train each way', { overnight: true })],
      bengaluru: [fl(3, 7000, 'Direct flight, then about an hour to the beaches'), tr(14, 1400, 'Overnight via Londa', { overnight: true }), rd(12, 2200, 'Overnight sleeper bus', { overnight: true })],
      pune: [fl(3, 6500, 'Direct flight, then a transfer to the beaches'), rd(9, 1800, 'Daytime drive or a morning Volvo down NH48'), tr(12, 1400, 'Overnight on the Konkan line', { overnight: true })],
      chennai: [fl(3.5, 8000, 'Direct flight, then about an hour to the beaches'), tr(21, 1800, 'Long haul via Bengaluru, overnight', { overnight: true })],
      hyderabad: [fl(3, 7000, 'Direct flight, then a transfer'), tr(17, 1600, 'Overnight via Vasco', { overnight: true }), rd(12, 2000, 'Overnight sleeper bus', { overnight: true })],
      kolkata: [fl(5, 10500, 'Direct flight, then a transfer to the beaches'), tr(38, 2600, 'Two nights on the train each way', { overnight: true })],
    }),
  },
  {
    id: 'gokarna',
    name: 'Gokarna',
    region: 'Karnataka coast',
    blurb: 'Quieter beaches than Goa, cliff walks between them, and a slower pace that suits a group that wants to actually talk to each other.',
    vibes: ['beach', 'nature', 'relaxation'],
    nightlife: 'some',
    dailyCost: { budget: 1600, mid: 3600, premium: 7500 },
    stayTypes: { budget: 'Beach huts and hostel dorms above Kudle', mid: 'Mid-range beach resorts and sea-view rooms', premium: 'Cliffside boutique properties with private access' },
    bestMonths: [10, 11, 12, 1, 2],
    idealDays: [3, 6],
    octoberRating: 'good',
    octoberNote: 'The sea settles after the monsoon; early October can still see a stray shower.',
    routes: routes({
      mumbai: [fl(5.5, 7500, 'Fly to Goa, then about 2.5 hrs down the coast by road'), tr(13, 1500, 'Konkan Railway to Gokarna Road, overnight', { overnight: true })],
      delhi: [fl(7, 11500, 'Fly to Goa, then about 2.5 hrs by road'), tr(30, 2600, 'Two nights on the train each way', { overnight: true })],
      bengaluru: [fl(5, 8500, 'Fly to Goa, then about 2.5 hrs by road'), rd(10, 1600, 'Overnight sleeper bus via Hubballi', { overnight: true }), tr(11, 1200, 'Overnight train to Gokarna Road', { overnight: true })],
      pune: [fl(5.5, 9000, 'Fly to Goa, then about 2.5 hrs by road'), rd(12, 1800, 'Overnight sleeper bus', { overnight: true })],
      chennai: [fl(7, 10500, 'Fly to Goa, then about 2.5 hrs by road'), tr(19, 1700, 'Overnight via Bengaluru', { overnight: true })],
      hyderabad: [fl(6, 9500, 'Fly to Goa, then about 2.5 hrs by road'), rd(14, 2000, 'Overnight sleeper bus', { overnight: true })],
      kolkata: [fl(8, 12500, 'Fly to Goa, then about 2.5 hrs by road'), tr(40, 2800, 'Two nights on the train each way', { overnight: true })],
    }),
  },
  {
    id: 'coorg',
    name: 'Coorg',
    region: 'Karnataka hills',
    blurb: 'Coffee estates, misty mornings and short walks to waterfalls. Cool without being a Himalayan expedition.',
    vibes: ['nature', 'relaxation', 'wellness', 'adventure'],
    nightlife: 'none',
    dailyCost: { budget: 1900, mid: 4300, premium: 9000 },
    stayTypes: { budget: 'Homestay dorms and shared estate rooms', mid: 'Estate homestays and mid-range resorts with private rooms', premium: 'Plantation villas and spa resorts' },
    bestMonths: [10, 11, 12, 1, 2, 3],
    idealDays: [3, 5],
    octoberRating: 'excellent',
    octoberNote: 'Post-monsoon green, waterfalls still full, and the coffee blossom season approaching.',
    routes: routes({
      mumbai: [fl(5.5, 8500, 'Fly to Mangaluru, then about 3.5 hrs by road into the hills'), fl(6.5, 8000, 'Fly to Bengaluru, then about 6 hrs by road')],
      delhi: [fl(9, 11000, 'Fly to Bengaluru, then about 6 hrs by road'), fl(8, 12000, 'Fly to Mangaluru, then about 3.5 hrs by road')],
      bengaluru: [rd(6, 1800, 'Daytime drive on NH275, or a morning Volvo to Madikeri'), rd(7, 1400, 'Overnight KSRTC bus to Madikeri', { overnight: true })],
      pune: [fl(8, 9500, 'Fly to Bengaluru, then about 6 hrs by road'), fl(7, 9000, 'Fly to Mangaluru, then about 3.5 hrs by road')],
      chennai: [fl(9, 9000, 'Fly to Bengaluru, then about 6 hrs by road'), rd(11, 2000, 'Overnight bus via Mysuru', { overnight: true })],
      hyderabad: [fl(8.5, 9500, 'Fly to Bengaluru, then about 6 hrs by road'), rd(15, 2400, 'Overnight bus via Bengaluru', { overnight: true })],
      kolkata: [fl(10, 13000, 'Fly to Bengaluru, then about 6 hrs by road')],
    }),
  },
  {
    id: 'pondicherry',
    name: 'Pondicherry',
    region: 'Tamil Nadu coast',
    blurb: 'French-quarter streets, some of the best food in the south, and Auroville twenty minutes away. The seafront is a promenade, not a swimming beach.',
    vibes: ['culture', 'food', 'relaxation'],
    nightlife: 'some',
    dailyCost: { budget: 1800, mid: 4000, premium: 8500 },
    stayTypes: { budget: 'Hostels and guesthouse dorms off the Tamil quarter', mid: 'Heritage guesthouses and mid-range hotels with private rooms', premium: 'Restored colonial villas and seafront boutique hotels' },
    bestMonths: [10, 11, 12, 1, 2, 3],
    idealDays: [2, 4],
    octoberRating: 'good',
    octoberNote: 'Pleasant, though the north-east monsoon can bring showers late in the month.',
    routes: routes({
      mumbai: [fl(6, 8500, 'Fly to Chennai, then about 3 hrs down the ECR'), tr(27, 2200, 'Overnight to Chennai, then road', { overnight: true })],
      delhi: [fl(7, 10500, 'Fly to Chennai, then about 3 hrs down the ECR')],
      bengaluru: [rd(6, 1500, 'Daytime drive via Tindivanam, or a morning bus'), rd(7, 1200, 'Overnight bus', { overnight: true })],
      pune: [fl(6.5, 9000, 'Fly to Chennai, then about 3 hrs by road')],
      chennai: [rd(3, 900, 'Straightforward drive down the East Coast Road'), tr(4, 500, 'Train to Villupuram, then a short hop')],
      hyderabad: [fl(6, 8500, 'Fly to Chennai, then about 3 hrs by road'), tr(16, 1600, 'Overnight to Chennai, then road', { overnight: true })],
      kolkata: [fl(7.5, 11000, 'Fly to Chennai, then about 3 hrs by road')],
    }),
  },
  {
    id: 'varkala',
    name: 'Varkala',
    region: 'Kerala coast',
    blurb: 'A beach at the bottom of a red cliff, cafés along the top, and Ayurveda everywhere you look.',
    vibes: ['beach', 'wellness', 'relaxation', 'nature'],
    nightlife: 'some',
    dailyCost: { budget: 1700, mid: 3900, premium: 8000 },
    stayTypes: { budget: 'Cliff-top hostels and shared cottages', mid: 'Cliff-edge guesthouses and mid-range resorts', premium: 'Private-pool villas and Ayurveda retreats' },
    bestMonths: [11, 12, 1, 2, 3],
    idealDays: [3, 6],
    octoberRating: 'poor',
    octoberNote: 'Still the tail of the south-west monsoon: rough seas, red flags on the beach, and the season does not really open until November.',
    routes: routes({
      mumbai: [fl(5, 8500, 'Fly to Trivandrum, then about 1.5 hrs by road')],
      delhi: [fl(6.5, 11500, 'Fly to Trivandrum, then about 1.5 hrs by road')],
      bengaluru: [fl(4.5, 8000, 'Fly to Trivandrum, then about 1.5 hrs by road'), tr(17, 1600, 'Overnight train down the coast', { overnight: true })],
      pune: [fl(5, 9000, 'Fly to Trivandrum, then about 1.5 hrs by road')],
      chennai: [fl(4.5, 8000, 'Fly to Trivandrum, then about 1.5 hrs by road'), tr(16, 1500, 'Overnight train via Kollam', { overnight: true })],
      hyderabad: [fl(5, 9000, 'Fly to Trivandrum, then about 1.5 hrs by road')],
      kolkata: [fl(7, 13000, 'Fly to Trivandrum, then about 1.5 hrs by road')],
    }),
  },
  {
    id: 'alibaug',
    name: 'Alibaug',
    region: 'Konkan coast',
    blurb: 'The short-hop beach weekend: quiet sand, a fort at low tide, and villas built for a group.',
    vibes: ['beach', 'relaxation'],
    nightlife: 'none',
    dailyCost: { budget: 1800, mid: 4200, premium: 9500 },
    stayTypes: { budget: 'Beach cottages and shared homestay rooms', mid: 'Mid-range resorts and private cottage rooms', premium: 'Whole villas with a pool, split across the group' },
    bestMonths: [10, 11, 12, 1, 2],
    idealDays: [2, 3],
    octoberRating: 'good',
    octoberNote: 'Drying out after the monsoon and still green; the sea is calm by mid-month.',
    routes: routes({
      mumbai: [rd(2, 600, 'Ferry from Gateway plus a short drive, or drive round via the coastal road')],
      delhi: [fl(5.5, 9500, 'Fly to Mumbai, then the ferry and a short drive')],
      bengaluru: [fl(4.5, 7500, 'Fly to Mumbai, then the ferry and a short drive')],
      pune: [rd(3.5, 1000, 'Drive over the ghats via Khopoli')],
      chennai: [fl(5, 8500, 'Fly to Mumbai, then the ferry and a short drive')],
      hyderabad: [fl(4.5, 7500, 'Fly to Mumbai, then the ferry and a short drive')],
      kolkata: [fl(6, 11000, 'Fly to Mumbai, then the ferry and a short drive')],
    }),
  },
  {
    id: 'udaipur',
    name: 'Udaipur',
    region: 'Rajasthan',
    blurb: 'Lakes, palaces and rooftops. The most photogenic city in the country and easy to move around.',
    vibes: ['culture', 'city', 'food', 'relaxation'],
    nightlife: 'some',
    dailyCost: { budget: 2000, mid: 4600, premium: 11500 },
    stayTypes: { budget: 'Old-city hostels and shared haveli rooms', mid: 'Heritage havelis with lake-view private rooms', premium: 'Palace hotels and lakeside luxury properties' },
    bestMonths: [10, 11, 12, 1, 2, 3],
    idealDays: [3, 5],
    octoberRating: 'excellent',
    octoberNote: 'The lakes are full after the monsoon and the heat has broken.',
    routes: routes({
      mumbai: [fl(4, 7000, 'Direct flight, then a short drive into the old city'), tr(16, 1600, 'Overnight train', { overnight: true })],
      delhi: [fl(3.5, 6500, 'Direct flight, then a short drive'), tr(12, 1400, 'Overnight train via Ajmer', { overnight: true }), rd(11, 1800, 'Overnight bus', { overnight: true })],
      bengaluru: [fl(5, 9500, 'Direct flight, then a short drive')],
      pune: [fl(4.5, 8000, 'Fly via Mumbai or direct, then a short drive'), tr(18, 1700, 'Overnight train', { overnight: true })],
      chennai: [fl(5.5, 10000, 'Fly via a connection, then a short drive')],
      hyderabad: [fl(4.5, 8500, 'Fly via a connection, then a short drive')],
      kolkata: [fl(6, 11000, 'Fly via Delhi, then a short drive')],
    }),
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    region: 'Rajasthan',
    blurb: 'Forts, bazaars and a genuinely good food scene, with enough going on that nobody gets bored.',
    vibes: ['culture', 'city', 'food', 'nightlife'],
    nightlife: 'some',
    dailyCost: { budget: 1900, mid: 4400, premium: 10500 },
    stayTypes: { budget: 'Hostels and shared rooms near the old city', mid: 'Boutique hotels and heritage guesthouses', premium: 'Palace hotels and luxury resorts on the edge of town' },
    bestMonths: [10, 11, 12, 1, 2, 3],
    idealDays: [3, 5],
    octoberRating: 'excellent',
    octoberNote: 'Cool mornings, warm afternoons, and the festival season starting.',
    routes: routes({
      mumbai: [fl(3.5, 6500, 'Direct flight, then a short drive'), tr(18, 1700, 'Overnight train', { overnight: true })],
      delhi: [rd(5.5, 1200, 'Daytime drive on the expressway'), tr(4.5, 900, 'Morning Vande Bharat or Shatabdi'), fl(3, 5000, 'Short hop, though the road is usually easier')],
      bengaluru: [fl(4.5, 8500, 'Direct flight, then a short drive')],
      pune: [fl(4, 7500, 'Direct flight, then a short drive')],
      chennai: [fl(5, 9500, 'Direct flight, then a short drive')],
      hyderabad: [fl(4, 8000, 'Direct flight, then a short drive')],
      kolkata: [fl(4.5, 9000, 'Direct flight, then a short drive'), tr(30, 2400, 'Two nights on the train each way', { overnight: true })],
    }),
  },
  {
    id: 'hampi',
    name: 'Hampi',
    region: 'Karnataka interior',
    blurb: 'Boulder fields and ruined temples spread over miles. Extraordinary to look at, light on comfort.',
    vibes: ['culture', 'nature', 'adventure'],
    nightlife: 'none',
    dailyCost: { budget: 1300, mid: 3200, premium: 7000 },
    stayTypes: { budget: 'Guesthouse dorms across the river in Anegundi', mid: 'Mid-range resorts with private rooms and AC', premium: 'Boutique heritage-style resorts (the most comfortable option here)' },
    bestMonths: [10, 11, 12, 1, 2],
    idealDays: [3, 5],
    octoberRating: 'good',
    octoberNote: 'Cooling down but still warm in the middle of the day; the river is high and green.',
    routes: routes({
      mumbai: [fl(7, 8500, 'Fly to Hubballi, then about 3 hrs by road'), tr(15, 1500, 'Overnight train to Hospet', { overnight: true })],
      delhi: [fl(8.5, 12000, 'Fly to Hubballi, then about 3 hrs by road')],
      bengaluru: [rd(7, 1400, 'Overnight sleeper bus to Hospet', { overnight: true }), tr(8, 1100, 'Overnight train to Hospet', { overnight: true }), fl(5, 7500, 'Fly to Hubballi, then about 3 hrs by road')],
      pune: [fl(6.5, 8000, 'Fly to Hubballi, then about 3 hrs by road'), rd(11, 1600, 'Overnight bus', { overnight: true })],
      chennai: [tr(12, 1300, 'Overnight train to Hospet', { overnight: true }), fl(7, 8500, 'Fly via Bengaluru, then about 3 hrs by road')],
      hyderabad: [rd(9, 1400, 'Overnight bus', { overnight: true }), tr(10, 1200, 'Overnight train', { overnight: true })],
      kolkata: [fl(10, 13500, 'Fly via Bengaluru, then about 3 hrs by road')],
    }),
  },
  {
    id: 'munnar',
    name: 'Munnar',
    region: 'Kerala hills',
    blurb: 'Tea terraces to the horizon, cold mornings and short treks. Very green, very quiet.',
    vibes: ['nature', 'relaxation', 'wellness', 'adventure'],
    nightlife: 'none',
    dailyCost: { budget: 1700, mid: 4000, premium: 8500 },
    stayTypes: { budget: 'Homestay dorms and shared rooms in town', mid: 'Tea-estate homestays and mid-range resorts', premium: 'Plantation bungalows and spa resorts on the ridge' },
    bestMonths: [10, 11, 12, 1, 2, 3],
    idealDays: [3, 5],
    octoberRating: 'good',
    octoberNote: 'The monsoon is easing and the tea slopes are at their greenest; mornings are cold.',
    routes: routes({
      mumbai: [fl(7, 8500, 'Fly to Kochi, then about 4 hrs up into the hills')],
      delhi: [fl(8.5, 11500, 'Fly to Kochi, then about 4 hrs by road')],
      bengaluru: [fl(6.5, 7500, 'Fly to Kochi, then about 4 hrs by road'), rd(12, 1800, 'Overnight bus via Salem', { overnight: true })],
      pune: [fl(7, 9000, 'Fly to Kochi, then about 4 hrs by road')],
      chennai: [fl(6.5, 8000, 'Fly to Kochi, then about 4 hrs by road'), rd(12, 1700, 'Overnight bus', { overnight: true })],
      hyderabad: [fl(7, 9000, 'Fly to Kochi, then about 4 hrs by road')],
      kolkata: [fl(9, 13000, 'Fly to Kochi, then about 4 hrs by road')],
    }),
  },
  {
    id: 'wayanad',
    name: 'Wayanad',
    region: 'Kerala hills',
    blurb: 'Forest, caves and waterfalls with fewer people than Munnar, and easy to reach from the south.',
    vibes: ['nature', 'adventure', 'relaxation', 'wellness'],
    nightlife: 'none',
    dailyCost: { budget: 1700, mid: 3900, premium: 8200 },
    stayTypes: { budget: 'Homestay dorms and shared plantation rooms', mid: 'Treehouse and estate stays with private rooms', premium: 'Luxury forest resorts and private villas' },
    bestMonths: [10, 11, 12, 1, 2, 3],
    idealDays: [3, 5],
    octoberRating: 'excellent',
    octoberNote: 'Post-monsoon at its best: full waterfalls, clear forest trails, cool evenings.',
    routes: routes({
      mumbai: [fl(6, 8500, 'Fly to Kozhikode, then about 2.5 hrs up the ghat')],
      delhi: [fl(8, 11500, 'Fly to Kozhikode, then about 2.5 hrs by road')],
      bengaluru: [rd(7, 1500, 'Daytime drive via Mysuru, or a morning bus'), rd(8, 1300, 'Overnight bus', { overnight: true })],
      pune: [fl(6.5, 9000, 'Fly to Kozhikode, then about 2.5 hrs by road')],
      chennai: [fl(6.5, 8000, 'Fly to Kozhikode, then about 2.5 hrs by road'), rd(13, 1800, 'Overnight bus', { overnight: true })],
      hyderabad: [fl(7, 9000, 'Fly to Kozhikode, then about 2.5 hrs by road')],
      kolkata: [fl(9, 13000, 'Fly to Kozhikode, then about 2.5 hrs by road')],
    }),
  },
  {
    id: 'manali',
    name: 'Manali',
    region: 'Himachal Pradesh',
    blurb: 'Proper mountains: snow on the passes, river-side cafés and everything from rafting to a very slow morning.',
    vibes: ['mountains', 'adventure', 'nature', 'nightlife'],
    nightlife: 'some',
    dailyCost: { budget: 1500, mid: 3800, premium: 8500 },
    stayTypes: { budget: 'Old Manali hostels and shared rooms', mid: 'Riverside hotels and cottages with private rooms', premium: 'Boutique mountain resorts and private chalets' },
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    idealDays: [4, 8],
    octoberRating: 'excellent',
    octoberNote: 'Clear skies, autumn colour and the first snow on the high passes.',
    routes: routes({
      mumbai: [fl(11, 12000, 'Fly to Chandigarh, then about 8 hrs by road up the valley'), fl(12, 14500, 'Fly to Bhuntar via Delhi, then about 1.5 hrs by road')],
      delhi: [rd(12, 1800, 'Overnight Volvo up NH3 — the standard way to do it', { overnight: true }), fl(5, 11000, 'Fly to Bhuntar, then about 1.5 hrs by road', { early: true }), rd(13, 4500, 'Daytime drive with a stop, or a private cab')],
      bengaluru: [fl(14, 14000, 'Fly to Delhi, then the overnight bus up the valley', { overnight: true }), fl(9, 16500, 'Fly to Bhuntar via Delhi, then about 1.5 hrs by road')],
      pune: [fl(13, 13000, 'Fly to Delhi, then the overnight bus', { overnight: true }), fl(9, 15500, 'Fly to Bhuntar via Delhi, then about 1.5 hrs by road')],
      chennai: [fl(15, 14500, 'Fly to Delhi, then the overnight bus', { overnight: true })],
      hyderabad: [fl(14, 13500, 'Fly to Delhi, then the overnight bus', { overnight: true })],
      kolkata: [fl(14, 13000, 'Fly to Delhi, then the overnight bus', { overnight: true })],
    }),
  },
  {
    id: 'kasol',
    name: 'Kasol',
    region: 'Parvati Valley',
    blurb: 'A river, pine forest and a valley full of trails. Cheap, scruffy and beautiful.',
    vibes: ['mountains', 'nature', 'adventure', 'relaxation'],
    nightlife: 'some',
    dailyCost: { budget: 1200, mid: 3000, premium: 6500 },
    stayTypes: { budget: 'Riverside hostels and camp dorms', mid: 'Guesthouses and cottages with private rooms', premium: 'Boutique riverside stays (limited at this end of the valley)' },
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    idealDays: [4, 8],
    octoberRating: 'good',
    octoberNote: 'Cold and clear, with autumn colour in the valley. Nights drop close to freezing.',
    routes: routes({
      mumbai: [fl(11, 12500, 'Fly to Delhi, then the overnight bus up the valley', { overnight: true })],
      delhi: [rd(12, 1600, 'Overnight Volvo to Bhuntar, then a short hop', { overnight: true }), fl(5.5, 11000, 'Fly to Bhuntar, then about an hour by road', { early: true })],
      bengaluru: [fl(14, 14500, 'Fly to Delhi, then the overnight bus', { overnight: true })],
      pune: [fl(13, 13500, 'Fly to Delhi, then the overnight bus', { overnight: true })],
      chennai: [fl(15, 15000, 'Fly to Delhi, then the overnight bus', { overnight: true })],
      hyderabad: [fl(14, 14000, 'Fly to Delhi, then the overnight bus', { overnight: true })],
      kolkata: [fl(14, 13500, 'Fly to Delhi, then the overnight bus', { overnight: true })],
    }),
  },
  {
    id: 'rishikesh',
    name: 'Rishikesh',
    region: 'Uttarakhand',
    blurb: 'The Ganga coming out of the hills: rafting in the morning, yoga in the evening, no alcohol anywhere.',
    vibes: ['adventure', 'wellness', 'nature', 'mountains'],
    nightlife: 'none',
    dailyCost: { budget: 1300, mid: 3200, premium: 7500 },
    stayTypes: { budget: 'Riverside hostels and ashram dorms', mid: 'Mid-range hotels and camps with private rooms', premium: 'Riverside wellness resorts' },
    bestMonths: [2, 3, 4, 9, 10, 11],
    idealDays: [3, 6],
    octoberRating: 'excellent',
    octoberNote: 'The river has settled after the monsoon and rafting season is fully open.',
    routes: routes({
      mumbai: [fl(6, 9000, 'Fly to Dehradun, then about an hour by road'), tr(28, 2200, 'Overnight train via Delhi', { overnight: true })],
      delhi: [rd(6, 1000, 'Daytime drive on the expressway, or a morning bus'), tr(5.5, 800, 'Morning train to Haridwar, then a short hop'), rd(7, 900, 'Overnight bus', { overnight: true })],
      bengaluru: [fl(7, 11000, 'Fly to Dehradun via Delhi, then about an hour by road')],
      pune: [fl(6.5, 10000, 'Fly to Dehradun, then about an hour by road')],
      chennai: [fl(7.5, 11500, 'Fly to Dehradun via Delhi, then about an hour by road')],
      hyderabad: [fl(7, 10500, 'Fly to Dehradun via Delhi, then about an hour by road')],
      kolkata: [fl(6.5, 10000, 'Fly to Dehradun via Delhi, then about an hour by road')],
    }),
  },
  {
    id: 'mcleodganj',
    name: 'McLeod Ganj',
    region: 'Himachal Pradesh',
    blurb: 'Tibetan food, monasteries and the Triund trek, with the Dhauladhar range right above you.',
    vibes: ['mountains', 'culture', 'nature', 'wellness'],
    nightlife: 'none',
    dailyCost: { budget: 1300, mid: 3200, premium: 7000 },
    stayTypes: { budget: 'Hostels and shared rooms on the Bhagsu road', mid: 'Guesthouses and hotels with mountain-view private rooms', premium: 'Boutique properties in Naddi with valley views' },
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    idealDays: [4, 7],
    octoberRating: 'excellent',
    octoberNote: 'The clearest month of the year for the Dhauladhar range.',
    routes: routes({
      mumbai: [fl(9, 12000, 'Fly to Dharamshala via Delhi, then a short climb by road'), fl(11, 10500, 'Fly to Delhi, then the overnight bus', { overnight: true })],
      delhi: [rd(11, 1600, 'Overnight Volvo to Dharamshala', { overnight: true }), fl(4.5, 9500, 'Fly to Gaggal, then about 45 min by road')],
      bengaluru: [fl(10, 14000, 'Fly to Dharamshala via Delhi, then a short climb by road')],
      pune: [fl(9.5, 13000, 'Fly to Dharamshala via Delhi, then a short climb by road')],
      chennai: [fl(11, 14500, 'Fly to Dharamshala via Delhi, then a short climb by road')],
      hyderabad: [fl(10, 13500, 'Fly to Dharamshala via Delhi, then a short climb by road')],
      kolkata: [fl(10, 13000, 'Fly to Dharamshala via Delhi, then a short climb by road')],
    }),
  },
  {
    id: 'darjeeling',
    name: 'Darjeeling',
    region: 'West Bengal hills',
    blurb: 'Tea gardens, the toy train, and Kanchenjunga on a clear morning.',
    vibes: ['mountains', 'nature', 'culture', 'relaxation'],
    nightlife: 'none',
    dailyCost: { budget: 1400, mid: 3400, premium: 7500 },
    stayTypes: { budget: 'Hostels and shared homestay rooms', mid: 'Heritage guesthouses and hotels with private rooms', premium: 'Colonial-era hotels and tea-estate bungalows' },
    bestMonths: [3, 4, 5, 10, 11, 12],
    idealDays: [4, 7],
    octoberRating: 'excellent',
    octoberNote: 'The clearest mountain views of the year, right after the monsoon.',
    routes: routes({
      mumbai: [fl(9, 12500, 'Fly to Bagdogra, then about 3.5 hrs up the hill')],
      delhi: [fl(8.5, 11500, 'Fly to Bagdogra, then about 3.5 hrs up the hill')],
      bengaluru: [fl(10, 13500, 'Fly to Bagdogra, then about 3.5 hrs up the hill')],
      pune: [fl(9.5, 13000, 'Fly to Bagdogra, then about 3.5 hrs up the hill')],
      chennai: [fl(10, 13500, 'Fly to Bagdogra, then about 3.5 hrs up the hill')],
      hyderabad: [fl(9.5, 12500, 'Fly to Bagdogra, then about 3.5 hrs up the hill')],
      kolkata: [fl(6, 8000, 'Fly to Bagdogra, then about 3.5 hrs up the hill'), tr(14, 1400, 'Overnight train to NJP, then about 3.5 hrs by road', { overnight: true })],
    }),
  },
  {
    id: 'andamans',
    name: 'Andaman Islands',
    region: 'Bay of Bengal',
    blurb: 'The clearest water in the country, proper diving, and genuinely empty beaches. You pay for all of it.',
    vibes: ['beach', 'nature', 'adventure', 'relaxation'],
    nightlife: 'none',
    dailyCost: { budget: 2800, mid: 6500, premium: 14000 },
    stayTypes: { budget: 'Havelock hostels and shared beach huts', mid: 'Mid-range island resorts with private rooms', premium: 'Beachfront luxury resorts on Havelock and Neil' },
    bestMonths: [11, 12, 1, 2, 3, 4],
    idealDays: [5, 9],
    octoberRating: 'fair',
    octoberNote: 'The monsoon is still withdrawing; ferries are occasionally cancelled in early October.',
    routes: routes({
      mumbai: [fl(9, 18000, 'Fly to Port Blair, then a 2 hr ferry to Havelock')],
      delhi: [fl(9.5, 19500, 'Fly to Port Blair, then a 2 hr ferry to Havelock')],
      bengaluru: [fl(8, 17000, 'Fly to Port Blair, then a 2 hr ferry to Havelock')],
      pune: [fl(9, 18500, 'Fly to Port Blair, then a 2 hr ferry to Havelock')],
      chennai: [fl(7, 15000, 'Fly to Port Blair, then a 2 hr ferry to Havelock')],
      hyderabad: [fl(8, 17000, 'Fly to Port Blair, then a 2 hr ferry to Havelock')],
      kolkata: [fl(7, 14500, 'Fly to Port Blair, then a 2 hr ferry to Havelock')],
    }),
  },
]
